name: Elm CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_elm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Elm tests
      run: |
        curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
        gunzip elm.gz
        chmod +x elm
        sudo mv elm /usr/local/bin/
        cd web
        npx elm-test@0.19.1-revision2
