name: Linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install Ruby dependencies
      run: |
        cd api
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: bin/lint
      run: bin/lint
